### ISSUE TITLE
Sumo

### ISSUE THREAD

**Issue by hmvp** [varigit/meta-variscite-fsl-community#11]
Do you have an ETA for sumo support? Can I use the master branch or is that not advised?

**Comment by floion** [comment]
+1 on this

**Comment by floion** [comment]
cc @eranmati maybe?

**Comment by varigigi** [comment]
Hi,
at the time being we don't consider Sumo mature enough and that's why we did not release sumo yet, but a release is very close.
Just to let you know, in meta-freescale, X11 xserver for iMX6 is still (up today) failing to start with Sumo branch.
Preliminary patches have been pushed to master branch only to fix runtime problems, but still persist 3D acceleration problems.
We are hardly working on this and an official release is very close.
Thanks
BR
Pier

**Comment by floion** [comment]
Thanks for the reply. Can we keep this issue open until the sumo branch is created?

**Comment by varigigi** [comment]
Hi,
there's no need to keep it open, the new release is in the air.
For faster support request management, please contact us through the customer portal:
   https://varisciteportal.axosoft.com/login
Thanks
BR
Pier
