### ISSUE TITLE
swupdate commandline tool does not take a -u parameter

### ISSUE THREAD

**Issue by elupus** [varigit/meta-variscite-fsl-community#34]
There seem to have snuck in a extra -u in the swupdate commandline for sysvinit:

https://github.com/varigit/meta-variscite-fslc/blob/3fa1b6b733dc806d7161e2252c5bd994e1822e17/dynamic-layers/swupdate/swupdate/swupdate#L67

This extra -u does not exist on the systemd version of init systems.

I've only checked this on dunfell distro.

**Comment by varigigi** [comment]
Hi Joakim,
the "-u" parameter is required to provide extra settings to suricatta client daemon:
    https://sbabic.github.io/swupdate/swupdate.html#command-line-parameters
Beyond this, the file you are referring is only used for sysVinit and not for systemd.
Assuming you are fine I'm now closing this issue.
Thanks
Best Regards
Pier

**Comment by elupus** [comment]
With suricata disabled, the init script fails... And as you mention this is for sysvinit not systemd. Why would this -u not be needed for systemd where it has been left out??

**Comment by varigigi** [comment]
Probably I'm missing the point, but our layer does enable surricata:
https://github.com/varigit/meta-variscite-fslc/blob/dunfell/dynamic-layers/swupdate/swupdate/defconfig#L47
Feel absolutely free to customize the defconfig, as well as the sysvinit script to fully remove suricatta support.
If you are suggesting to remove the -u options since present only in sysvinit (and not in systemd), I can agree with you, and we can consider it for one of the next releases.
Please let me know if you need further details.
Thanks
Best Regards
Pier

**Comment by elupus** [comment]
That is what i suggest. Seem weird to have it in one, but not the other. I will customize the layer for now. It just seemed like a quite common use case to only allow websever/mongose support and skipping support for the remote server.

**Comment by varigigi** [comment]
Thanks for the proposal, we will discuss this internally.
Please let me know if you need further assistance or I can close this issue.
Best Regards
Pier
